using RavenNest.DataAnnotations;
using System;

namespace RavenNest.DataModels
{
    public partial class NPC : Entity<NPC>
    {
        [PersistentData] private string name;
        [PersistentData] private int attack;
        [PersistentData] private int defense;
        [PersistentData] private int health;
        [PersistentData] private int weaponAim;
        [PersistentData] private int weaponPower;
        [PersistentData] private int armorPower;
        [PersistentData] private bool isStatsAutoGenerated;
        [PersistentData] private bool isAttackable;
        [PersistentData] private bool isAggressive;
        [PersistentData] private bool isRaidBoss;
        [PersistentData] private bool isDungeonBoss;
        [PersistentData] private string prefab;
    }
}
