-- Clan bank tables.
--
-- Run this by hand before the clan bank code ships. This project has no EF migrations and nothing
-- reconciles the schema at startup, and GameData loads every entity set eagerly at boot: adding a
-- DbSet for a table that does not exist takes the server down rather than degrading. So the tables
-- come first, the DbSets second.
--
-- Column types follow UserBankItem, which is the table the clan bank is a copy of with a different
-- owner column. Ids are uniqueidentifier and generated by the application, never by the database,
-- matching every other entity here.
--
-- Safe to run twice.

SET NOCOUNT ON;

-- ---------------------------------------------------------------------------------------------
-- What the clan holds. UserBankItem with clanId in place of userId.
-- ---------------------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ClanBankItem', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ClanBankItem
    (
        Id                    uniqueidentifier NOT NULL,
        ClanId                uniqueidentifier NOT NULL,
        ItemId                uniqueidentifier NOT NULL,
        Amount                bigint           NOT NULL CONSTRAINT DF_ClanBankItem_Amount DEFAULT (0),
        Name                  nvarchar(255)    NULL,
        Enchantment           nvarchar(512)    NULL,
        Tag                   nvarchar(255)    NULL,
        Soulbound             bit              NOT NULL CONSTRAINT DF_ClanBankItem_Soulbound DEFAULT (0),
        TransmogrificationId  uniqueidentifier NULL,
        Flags                 int              NOT NULL CONSTRAINT DF_ClanBankItem_Flags DEFAULT (0),

        CONSTRAINT PK_ClanBankItem PRIMARY KEY CLUSTERED (Id)
    );

    -- Reading the bank means reading one clan's rows, always.
    CREATE NONCLUSTERED INDEX IX_ClanBankItem_ClanId ON dbo.ClanBankItem (ClanId);

    PRINT 'Created dbo.ClanBankItem';
END
ELSE
    PRINT 'dbo.ClanBankItem already exists';


-- ---------------------------------------------------------------------------------------------
-- Who took what, and when.
--
-- Not optional. A shared bank without a log is a grief vector rather than a feature: the first
-- time somebody empties it the clan needs to know who, and without this the honest answer is that
-- nobody can tell. It is also what makes the daily allowance below cheap to enforce, since the
-- allowance is a sum over today's negative rows.
-- ---------------------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ClanBankLog', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ClanBankLog
    (
        Id           uniqueidentifier NOT NULL,
        ClanId       uniqueidentifier NOT NULL,
        CharacterId  uniqueidentifier NOT NULL,
        ItemId       uniqueidentifier NOT NULL,
        -- Negative for a withdrawal, positive for a deposit.
        Amount       bigint           NOT NULL,
        Time         datetime2(7)     NOT NULL CONSTRAINT DF_ClanBankLog_Time DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT PK_ClanBankLog PRIMARY KEY CLUSTERED (Id)
    );

    -- The log tab reads one clan newest first.
    CREATE NONCLUSTERED INDEX IX_ClanBankLog_ClanId_Time ON dbo.ClanBankLog (ClanId, Time DESC);

    -- The allowance check reads one character's rows for today.
    CREATE NONCLUSTERED INDEX IX_ClanBankLog_CharacterId_Time ON dbo.ClanBankLog (CharacterId, Time DESC);

    PRINT 'Created dbo.ClanBankLog';
END
ELSE
    PRINT 'dbo.ClanBankLog already exists';


-- ---------------------------------------------------------------------------------------------
-- How much a rank may take in a day.
--
-- A permission on its own is too blunt: "Officers can withdraw" means one bad Officer can take
-- everything. Keyed by rank level rather than by role id so a clan renaming or rebuilding its
-- ranks does not silently drop its limits.
-- ---------------------------------------------------------------------------------------------
IF OBJECT_ID(N'dbo.ClanBankWithdrawalLimit', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ClanBankWithdrawalLimit
    (
        Id          uniqueidentifier NOT NULL,
        ClanId      uniqueidentifier NOT NULL,
        RoleLevel   int              NOT NULL,
        -- -1 means no limit.
        ItemsPerDay int              NOT NULL CONSTRAINT DF_ClanBankWithdrawalLimit_ItemsPerDay DEFAULT (0),

        CONSTRAINT PK_ClanBankWithdrawalLimit PRIMARY KEY CLUSTERED (Id)
    );

    -- One row per rank per clan, so a duplicate cannot make which limit applies a question.
    CREATE UNIQUE NONCLUSTERED INDEX UX_ClanBankWithdrawalLimit_ClanId_RoleLevel
        ON dbo.ClanBankWithdrawalLimit (ClanId, RoleLevel);

    PRINT 'Created dbo.ClanBankWithdrawalLimit';
END
ELSE
    PRINT 'dbo.ClanBankWithdrawalLimit already exists';


-- ---------------------------------------------------------------------------------------------
-- No foreign keys, deliberately.
--
-- Nothing else in this schema declares them, and the application loads every set into memory and
-- writes them back in batches whose order it does not guarantee. Adding constraints here alone
-- would turn a save ordering detail into a failed write at some later date, which is a worse
-- problem than the one they would catch.
-- ---------------------------------------------------------------------------------------------

PRINT 'Clan bank schema ready. The DbSets can be added once this has run against the live database.';
